// Generated by CoffeeScript 1.3.3
(function() {

  window.FooterViewModel = function(todos) {
    var _this = this;
    this.todos = kb.collectionObservable(todos);
    this.todos.collection().bind('change', function() {
      return _this.todos.valueHasMutated();
    });
    this.remaining_text = ko.computed(function() {
      return "<strong>" + (_this.todos.collection().remainingCount()) + "</strong> " + (_this.todos.collection().remainingCount() === 1 ? 'item' : 'items') + " left";
    });
    this.clear_text = ko.computed(function() {
      var count;
      count = _this.todos.collection().completedCount();
      if (count) {
        return "Clear completed (" + count + ")";
      } else {
        return '';
      }
    });
    this.onDestroyCompleted = function() {
      return todos.destroyCompleted();
    };
    return this;
  };

}).call(this);
