// Generated by CoffeeScript 1.3.3
(function() {
  var ENTER_KEY;

  ENTER_KEY = 13;

  window.HeaderViewModel = function(todos) {
    var _this = this;
    this.title = ko.observable('');
    this.onAddTodo = function(view_model, event) {
      if (!$.trim(_this.title()) || (event.keyCode !== ENTER_KEY)) {
        return true;
      }
      todos.create({
        title: $.trim(_this.title())
      });
      return _this.title('');
    };
    return this;
  };

}).call(this);
