"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ESCAPE_KEY = exports.ENTER_KEY = exports.COMPLETED_TODOS = exports.ACTIVE_TODOS = exports.ALL_TODOS = void 0;
const ALL_TODOS = 'all';
exports.ALL_TODOS = ALL_TODOS;
const ACTIVE_TODOS = 'active';
exports.ACTIVE_TODOS = ACTIVE_TODOS;
const COMPLETED_TODOS = 'completed';
exports.COMPLETED_TODOS = COMPLETED_TODOS;
const ENTER_KEY = 13;
exports.ENTER_KEY = ENTER_KEY;
const ESCAPE_KEY = 27;
exports.ESCAPE_KEY = ESCAPE_KEY;
