jQuery.sap.registerPreloadedModules({
	"version": "2.0",
	"name": "js/Component-preload",
	"modules": {
		"js/Component.js": "sap.ui.define([\"sap/ui/core/UIComponent\"],function(t){\"use strict\";return t.extend(\"ToDoMVC.Component\",{metadata:{manifest:\"json\"},init:function(){t.prototype.init.apply(this,arguments),this.getRouter().initialize()}})});",
		"js/app.js": "!function(){\"use strict\";Function.prototype.bind||(Function.prototype.bind=function(t){if(\"function\"!=typeof this)throw new TypeError(\"Function.prototype.bind - what is trying to be bound is not callable\");var o=Array.prototype.slice.call(arguments,1),n=this,e=function(){},i=function(){return n.apply(this instanceof e?this:t,o.concat(Array.prototype.slice.call(arguments)))};return this.prototype&&(e.prototype=this.prototype),i.prototype=new e,i}),sap.ui.getCore().attachInit(function(){new sap.m.Shell({app:new sap.ui.core.ComponentContainer({height:\"100%\",name:\"ToDoMVC\"})}).placeAt(\"openui5\")})}(window);",
		"js/controller/App.controller.js": "sap.ui.define([\"sap/ui/core/mvc/Controller\"],function(e){\"use strict\";return e.extend(\"ToDoMVC.controller.App\",{})});",
		"js/controller/Home.controller.js": "sap.ui.define([\"sap/ui/core/mvc/Controller\",\"../control/ToDoControl\"],function(e,t){\"use strict\";return jQuery.sap.require(\"jquery.sap.storage\"),e.extend(\"ToDoMVC.controller.Home\",{onInit:function(){var e=sap.ui.core.UIComponent.getRouterFor(this);e.getRoute(\"appHomeFilter\").attachPatternMatched(this._onObjectMatched,this),e.getRoute(\"appHome\").attachPatternMatched(this._onObjectMatched,this);var o=jQuery.sap.storage(jQuery.sap.storage.Type.local);localStorage.getItem(\"0\")||localStorage.setItem(\"0\",0);var r=new sap.ui.model.json.JSONModel({allToDos:[],filterMode:\"all\"});this.getView().setModel(r),o.get(\"todos-openui5\")?r.setData(o.get(\"todos-openui5\")):o.put(\"todos-openui5\",r.getData());var a=new t({toDosObject:\"{/allToDos}\",filter:\"{/filterMode}\",addToDoPressed:function(e){localStorage.setItem(\"0\",+localStorage.getItem(\"0\")+1),r.getProperty(\"/allToDos\").push({id:+localStorage.getItem(\"0\"),title:e.getParameter(\"title\"),completed:!1}),o.put(\"todos-openui5\",r.getData()),r.refresh(!0)},deleteToDoPressed:function(e){var t=r.getProperty(\"/allToDos\");t.some(function(o,r){return o.id===+e.getParameter(\"toDoId\")?(t.splice(r,1),!0):void 0},this),o.put(\"todos-openui5\",r.getData()),r.refresh(!0)},deleteAllCompletedToDosPressed:function(e){for(var t=r.getProperty(\"/allToDos\"),a=e.getParameter(\"toDoIds\"),s=function(e,o){return+a[0]===e.id?(t.splice(o,1),a.splice(0,1),!0):void 0};a.length>0;)t.some(s,this);o.put(\"todos-openui5\",r.getData()),r.refresh(!0)},completedToDoPressed:function(e){var t=r.getProperty(\"/allToDos\");t.some(function(t){return t.id===+e.getParameter(\"toDoId\")?(t.completed=e.getParameter(\"completed\"),!0):void 0},this),o.put(\"todos-openui5\",r.getData()),r.refresh(!0)},toDoChangedPressed:function(e){var t=r.getProperty(\"/allToDos\");t.some(function(t){return t.id===+e.getParameter(\"toDoId\")?(t.title=e.getParameter(\"title\"),!0):void 0},this),o.put(\"todos-openui5\",r.getData()),r.refresh(!0)}});this.getView().getContent()[0].addContent(a)},_onObjectMatched:function(e){if(e.getParameter(\"arguments\").filter){var t=e.getParameter(\"arguments\").filter.replace(/[^\\w]/gi,\"\");\"active\"!==t&&\"completed\"!==t||this.getView().getModel().setProperty(\"/filterMode\",t)}else this.getView().getModel().setProperty(\"/filterMode\",\"all\");jQuery.sap.storage(jQuery.sap.storage.Type.local).put(\"todos-openui5\",this.getView().getModel().getData()),this.getView().getModel().refresh(!0)}})});",
		"js/manifest.json": "{\"_version\":\"1.1.0\",\"sap.app\":{\"_version\":\"1.1.0\",\"id\":\"ToDoMVC\",\"type\":\"application\",\"i18n\":\"i18n/i18n.properties\",\"applicationVersion\":{\"version\":\"1.0.0\"}},\"sap.ui\":{\"_version\":\"1.1.0\",\"technology\":\"UI5\",\"deviceTypes\":{\"desktop\":true,\"tablet\":true,\"phone\":true}},\"sap.ui5\":{\"_version\":\"1.1.0\",\"rootView\":{\"viewName\":\"ToDoMVC.view.App\",\"type\":\"XML\"},\"dependencies\":{\"minUI5Version\":\"1.30.0\",\"libs\":{\"sap.m\":{}}},\"models\":{\"i18n\":{\"type\":\"sap.ui.model.resource.ResourceModel\",\"settings\":{\"bundleName\":\"ToDoMVC.i18n.i18n\"}}},\"routing\":{\"config\":{\"routerClass\":\"sap.m.routing.Router\",\"viewType\":\"XML\",\"viewPath\":\"ToDoMVC.view\",\"controlId\":\"app\",\"controlAggregation\":\"pages\"},\"routes\":[{\"pattern\":\"\",\"name\":\"appHome\",\"target\":\"home\"},{\"pattern\":\"{filter}\",\"name\":\"appHomeFilter\",\"target\":\"home\"}],\"targets\":{\"home\":{\"viewName\":\"Home\",\"viewLevel\":1}}}}}",
		"js/view/App.view.xml": "<mvc:View controllerName=\"ToDoMVC.controller.App\" xmlns=\"sap.m\" xmlns:mvc=\"sap.ui.core.mvc\" displayBlock=\"true\"><App id=\"app\"/></mvc:View>\n",
		"js/view/Home.view.xml": "<mvc:View controllerName=\"ToDoMVC.controller.Home\" xmlns:mvc=\"sap.ui.core.mvc\" xmlns=\"sap.m\"><Page showHeader=\"false\"/></mvc:View>\n",
		"js/i18n/i18n_en.properties": "# Component\nappTitle=OpenUI5 • TodoMVC\nappDescription=\n\n# Custom Control\ntitle=todos\nnewTodo=What needs to be done?\nmarkAllAsComplete=Mark all as complete\nclearCompleted=Clear completed\nall=All\nactive=Active\ncompleted=Completed\ndoubleClickInfo=Double-click to edit a todo\ncredits=Written by\npartOf=Part of\nmultipleLeft=items left\nsingleLeft=item left\n"
	}
});