// Generated by CoffeeScript 1.9.1
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.Todo = (function(superClass) {
    extend(Todo, superClass);

    function Todo() {
      return Todo.__super__.constructor.apply(this, arguments);
    }

    Todo.configure('Todo', 'title', 'completed');

    Todo.extend(Spine.Model.Local);

    Todo.active = function() {
      return this.select(function(todo) {
        return !todo.completed;
      });
    };

    Todo.completed = function() {
      return this.select(function(todo) {
        return !!todo.completed;
      });
    };

    Todo.destroyCompleted = function() {
      var i, len, ref, results, todo;
      ref = this.completed();
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        todo = ref[i];
        results.push(todo.destroy());
      }
      return results;
    };

    return Todo;

  })(Spine.Model);

}).call(this);
