define(
//begin v1.x content
{
	"dateFormatItem-yM": "L.yyyy",
	"dateFormatItem-yyyyMMMEd": "EEE d. MMM y G",
	"dateFormatItem-yQ": "Q/yyyy",
	"dayPeriods-format-wide-pm": "ip.",
	"dateFormatItem-MMMEd": "E d. MMM",
	"dateFormatItem-hms": "h.mm.ss a",
	"dateFormatItem-yQQQ": "QQQ y",
	"days-standAlone-wide": [
		"sunnuntai",
		"maanantai",
		"tiistai",
		"keskiviikko",
		"torstai",
		"perjantai",
		"lauantai"
	],
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-Gy": "y G",
	"dayPeriods-format-wide-am": "ap.",
	"dateFormatItem-y": "y G",
	"timeFormat-full": "H.mm.ss zzzz",
	"dateFormatItem-yyyy": "y G",
	"months-standAlone-abbr": [
		"muharram",
		"safar",
		"rabi’ al-awwal",
		"rabi’ al-akhir",
		"džumada-l-ula",
		"džumada-l-akhira",
		"radžab",
		"ša’ban",
		"ramadan",
		"šawwal",
		"dhu-l-qa’da",
		"dhu-l-hiddža"
	],
	"dateFormatItem-Ed": "ccc d.",
	"dateFormatItem-yMMM": "LLL y",
	"days-standAlone-narrow": [
		"S",
		"M",
		"T",
		"K",
		"T",
		"P",
		"L"
	],
	"dateFormatItem-yyyyMMMMccccd": "cccc, d. MMMM y G",
	"dateFormatItem-yyyyMM": "M.y G",
	"dateFormatItem-yyyyMMMM": "LLLL y G",
	"dateFormat-long": "d. MMMM y G",
	"timeFormat-medium": "H.mm.ss",
	"dateFormatItem-Hm": "H.mm",
	"dateFormat-medium": "d.M.y G",
	"dateFormatItem-Hms": "H.mm.ss",
	"dateFormatItem-ms": "mm.ss",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"months-standAlone-wide": [
		"muharram",
		"safar",
		"rabi’ al-awwal",
		"rabi’ al-akhir",
		"džumada-l-ula",
		"džumada-l-akhira",
		"radžab",
		"ša’ban",
		"ramadan",
		"šawwal",
		"dhu-l-qa’da",
		"dhu-l-hiddža"
	],
	"dateFormatItem-yyyyMEd": "EEE d.M.y G",
	"dateFormatItem-MMMd": "d. MMM",
	"timeFormat-long": "H.mm.ss z",
	"months-format-abbr": [
		"muharram",
		"safar",
		"rabi’ al-awwal",
		"rabi’ al-akhir",
		"džumada-l-ula",
		"džumada-l-akhira",
		"radžab",
		"ša’ban",
		"ramadan",
		"šawwal",
		"dhu-l-qa’da",
		"dhu-l-hiddža"
	],
	"timeFormat-short": "H.mm",
	"dateFormatItem-H": "H",
	"quarters-format-abbr": [
		"1. nelj.",
		"2. nelj.",
		"3. nelj.",
		"4. nelj."
	],
	"days-format-abbr": [
		"su",
		"ma",
		"ti",
		"ke",
		"to",
		"pe",
		"la"
	],
	"dateFormatItem-M": "L",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateFormatItem-MEd": "E d.M.",
	"dateFormatItem-hm": "h.mm a",
	"dayPeriods-format-abbr-pm": "ip.",
	"dateFormat-short": "d.M.y G",
	"dateFormatItem-yyyyM": "M.y G",
	"dateFormatItem-yMMMEd": "EEE d. MMM y",
	"dateFormat-full": "cccc d. MMMM y G",
	"dateFormatItem-Md": "d.M.",
	"dateFormatItem-yyyyQ": "Q/y G",
	"dateFormatItem-yMEd": "EEE d.M.yyyy",
	"months-format-wide": [
		"muharram",
		"safar",
		"rabi’ al-awwal",
		"rabi’ al-akhir",
		"džumada-l-ula",
		"džumada-l-akhira",
		"radžab",
		"ša’ban",
		"ramadan",
		"šawwal",
		"dhu-l-qa’da",
		"dhu-l-hiddža"
	],
	"dayPeriods-format-abbr-am": "ap.",
	"dateFormatItem-yyyyMMM": "LLLL y G",
	"dateFormatItem-d": "d",
	"quarters-format-wide": [
		"1. neljännes",
		"2. neljännes",
		"3. neljännes",
		"4. neljännes"
	],
	"days-format-wide": [
		"sunnuntaina",
		"maanantaina",
		"tiistaina",
		"keskiviikkona",
		"torstaina",
		"perjantaina",
		"lauantaina"
	]
}
//end v1.x content
);