define(function () {
    /* Generated by PEG.js 0.6.2 (http://pegjs.majda.cz/). */

    var result = {
        /*
         * Parses the input with a generated parser. If the parsing is successfull,
         * returns a value explicitly or implicitly specified by the grammar from
         * which the parser was generated (see |PEG.buildParser|). If the parsing is
         * unsuccessful, throws |PEG.parser.SyntaxError| describing the error.
         */
        parse:function (input, startRule) {
            var parseFunctions = {
                "binding":parse_binding,
                "fnc":parse_fnc,
                "number":parse_number,
                "parameter":parse_parameter,
                "parameterArray":parse_parameterArray,
                "path":parse_path,
                "pathElement":parse_pathElement,
                "staticBinding":parse_staticBinding,
                "string":parse_string,
                "text":parse_text,
                "twoWayBinding":parse_twoWayBinding,
                "var":parse_var,
                "varName":parse_varName
            };

            if (startRule !== undefined) {
                if (parseFunctions[startRule] === undefined) {
                    throw new Error("Invalid rule name: " + quote(startRule) + ".");
                }
            } else {
                startRule = "text";
            }

            var pos = 0;
            var reportMatchFailures = true;
            var rightmostMatchFailuresPos = 0;
            var rightmostMatchFailuresExpected = [];
            var cache = {};

            function padLeft(input, padding, length) {
                var result = input;

                var padLength = length - input.length;
                for (var i = 0; i < padLength; i++) {
                    result = padding + result;
                }

                return result;
            }

            function escape(ch) {
                var charCode = ch.charCodeAt(0);

                if (charCode <= 0xFF) {
                    var escapeChar = 'x';
                    var length = 2;
                } else {
                    var escapeChar = 'u';
                    var length = 4;
                }

                return '\\' + escapeChar + padLeft(charCode.toString(16).toUpperCase(), '0', length);
            }

            function quote(s) {
                /*
                 * ECMA-262, 5th ed., 7.8.4: All characters may appear literally in a
                 * string literal except for the closing quote character, backslash,
                 * carriage return, line separator, paragraph separator, and line feed.
                 * Any character may appear in the form of an escape sequence.
                 */
                return '"' + s
                    .replace(/\\/g, '\\\\')// backslash
                    .replace(/"/g, '\\"')// closing quote character
                    .replace(/\r/g, '\\r')// carriage return
                    .replace(/\n/g, '\\n')// line feed
                    .replace(/[\x80-\uFFFF]/g, escape) // non-ASCII characters
                    + '"';
            }

            function matchFailed(failure) {
                if (pos < rightmostMatchFailuresPos) {
                    return;
                }

                if (pos > rightmostMatchFailuresPos) {
                    rightmostMatchFailuresPos = pos;
                    rightmostMatchFailuresExpected = [];
                }

                rightmostMatchFailuresExpected.push(failure);
            }

            function parse_varName() {
                var cacheKey = 'varName@' + pos;
                var cachedResult = cache[cacheKey];
                if (cachedResult) {
                    pos = cachedResult.nextPos;
                    return cachedResult.result;
                }


                var savedPos1 = pos;
                var savedPos2 = pos;
                if (input.substr(pos).match(/^[a-zA-Z$_]/) !== null) {
                    var result5 = input.charAt(pos);
                    pos++;
                } else {
                    var result5 = null;
                    if (reportMatchFailures) {
                        matchFailed("[a-zA-Z$_]");
                    }
                }
                if (result5 !== null) {
                    var result6 = [];
                    if (input.substr(pos).match(/^[a-zA-Z0-9$_\- ]/) !== null) {
                        var result7 = input.charAt(pos);
                        pos++;
                    } else {
                        var result7 = null;
                        if (reportMatchFailures) {
                            matchFailed("[a-zA-Z0-9$_\\- ]");
                        }
                    }
                    while (result7 !== null) {
                        result6.push(result7);
                        if (input.substr(pos).match(/^[a-zA-Z0-9$_\- ]/) !== null) {
                            var result7 = input.charAt(pos);
                            pos++;
                        } else {
                            var result7 = null;
                            if (reportMatchFailures) {
                                matchFailed("[a-zA-Z0-9$_\\- ]");
                            }
                        }
                    }
                    if (result6 !== null) {
                        var result3 = [result5, result6];
                    } else {
                        var result3 = null;
                        pos = savedPos2;
                    }
                } else {
                    var result3 = null;
                    pos = savedPos2;
                }
                var result4 = result3 !== null
                    ? (function (start, end) {
                    return start ? start + end.join("") : false;
                })(result3[0], result3[1])
                    : null;
                if (result4 !== null) {
                    var result2 = result4;
                } else {
                    var result2 = null;
                    pos = savedPos1;
                }
                if (result2 !== null) {
                    var result0 = result2;
                } else {
                    var savedPos0 = pos;
                    var result1 = [];
                    if (result1 !== null) {
                        var result0 = result1;
                    } else {
                        var result0 = null;
                        ;
                    }
                    ;
                }


                cache[cacheKey] = {
                    nextPos:pos,
                    result:result0
                };
                return result0;
            }

            function parse_var() {
                var cacheKey = 'var@' + pos;
                var cachedResult = cache[cacheKey];
                if (cachedResult) {
                    pos = cachedResult.nextPos;
                    return cachedResult.result;
                }


                var savedPos0 = pos;
                var result1 = parse_varName();
                var result2 = result1 !== null
                    ? (function (n) {
                    return {name:n, type:'var'};
                })(result1)
                    : null;
                if (result2 !== null) {
                    var result0 = result2;
                } else {
                    var result0 = null;
                    pos = savedPos0;
                }


                cache[cacheKey] = {
                    nextPos:pos,
                    result:result0
                };
                return result0;
            }

            function parse_string() {
                var cacheKey = 'string@' + pos;
                var cachedResult = cache[cacheKey];
                if (cachedResult) {
                    pos = cachedResult.nextPos;
                    return cachedResult.result;
                }


                var savedPos0 = pos;
                var savedPos1 = pos;
                if (input.substr(pos, 1) === "'") {
                    var result3 = "'";
                    pos += 1;
                } else {
                    var result3 = null;
                    if (reportMatchFailures) {
                        matchFailed("\"'\"");
                    }
                }
                if (result3 !== null) {
                    var result4 = [];
                    var savedPos2 = pos;
                    if (input.length > pos) {
                        var result7 = input.charAt(pos);
                        pos++;
                    } else {
                        var result7 = null;
                        if (reportMatchFailures) {
                            matchFailed('any character');
                        }
                    }
                    var result8 = result7 !== null
                        ? (function (char) {
                        return char === "'" ? null : char;
                    })(result7)
                        : null;
                    if (result8 !== null) {
                        var result6 = result8;
                    } else {
                        var result6 = null;
                        pos = savedPos2;
                    }
                    while (result6 !== null) {
                        result4.push(result6);
                        var savedPos2 = pos;
                        if (input.length > pos) {
                            var result7 = input.charAt(pos);
                            pos++;
                        } else {
                            var result7 = null;
                            if (reportMatchFailures) {
                                matchFailed('any character');
                            }
                        }
                        var result8 = result7 !== null
                            ? (function (char) {
                            return char === "'" ? null : char;
                        })(result7)
                            : null;
                        if (result8 !== null) {
                            var result6 = result8;
                        } else {
                            var result6 = null;
                            pos = savedPos2;
                        }
                    }
                    if (result4 !== null) {
                        if (input.substr(pos, 1) === "'") {
                            var result5 = "'";
                            pos += 1;
                        } else {
                            var result5 = null;
                            if (reportMatchFailures) {
                                matchFailed("\"'\"");
                            }
                        }
                        if (result5 !== null) {
                            var result1 = [result3, result4, result5];
                        } else {
                            var result1 = null;
                            pos = savedPos1;
                        }
                    } else {
                        var result1 = null;
                        pos = savedPos1;
                    }
                } else {
                    var result1 = null;
                    pos = savedPos1;
                }
                var result2 = result1 !== null
                    ? (function (s) {
                    return s.join("");
                })(result1[1])
                    : null;
                if (result2 !== null) {
                    var result0 = result2;
                } else {
                    var result0 = null;
                    pos = savedPos0;
                }


                cache[cacheKey] = {
                    nextPos:pos,
                    result:result0
                };
                return result0;
            }

            function parse_number() {
                var cacheKey = 'number@' + pos;
                var cachedResult = cache[cacheKey];
                if (cachedResult) {
                    pos = cachedResult.nextPos;
                    return cachedResult.result;
                }


                var savedPos0 = pos;
                if (input.substr(pos).match(/^[0-9]/) !== null) {
                    var result3 = input.charAt(pos);
                    pos++;
                } else {
                    var result3 = null;
                    if (reportMatchFailures) {
                        matchFailed("[0-9]");
                    }
                }
                if (result3 !== null) {
                    var result1 = [];
                    while (result3 !== null) {
                        result1.push(result3);
                        if (input.substr(pos).match(/^[0-9]/) !== null) {
                            var result3 = input.charAt(pos);
                            pos++;
                        } else {
                            var result3 = null;
                            if (reportMatchFailures) {
                                matchFailed("[0-9]");
                            }
                        }
                    }
                } else {
                    var result1 = null;
                }
                var result2 = result1 !== null
                    ? (function (digits) {
                    return parseInt(digits.join(""), 10);
                })(result1)
                    : null;
                if (result2 !== null) {
                    var result0 = result2;
                } else {
                    var result0 = null;
                    pos = savedPos0;
                }


                cache[cacheKey] = {
                    nextPos:pos,
                    result:result0
                };
                return result0;
            }

            function parse_parameter() {
                var cacheKey = 'parameter@' + pos;
                var cachedResult = cache[cacheKey];
                if (cachedResult) {
                    pos = cachedResult.nextPos;
                    return cachedResult.result;
                }


                var result4 = parse_string();
                if (result4 !== null) {
                    var result0 = result4;
                } else {
                    var result3 = parse_number();
                    if (result3 !== null) {
                        var result0 = result3;
                    } else {
                        var result2 = parse_staticBinding();
                        if (result2 !== null) {
                            var result0 = result2;
                        } else {
                            var result1 = parse_binding();
                            if (result1 !== null) {
                                var result0 = result1;
                            } else {
                                var result0 = null;
                                ;
                            }
                            ;
                        }
                        ;
                    }
                    ;
                }


                cache[cacheKey] = {
                    nextPos:pos,
                    result:result0
                };
                return result0;
            }

            function parse_parameterArray() {
                var cacheKey = 'parameterArray@' + pos;
                var cachedResult = cache[cacheKey];
                if (cachedResult) {
                    pos = cachedResult.nextPos;
                    return cachedResult.result;
                }


                var savedPos0 = pos;
                var savedPos1 = pos;
                var result10 = parse_parameter();
                var result3 = result10 !== null ? result10 : '';
                if (result3 !== null) {
                    var result4 = [];
                    var savedPos2 = pos;
                    var savedPos3 = pos;
                    if (input.substr(pos, 1) === ",") {
                        var result8 = ",";
                        pos += 1;
                    } else {
                        var result8 = null;
                        if (reportMatchFailures) {
                            matchFailed("\",\"");
                        }
                    }
                    if (result8 !== null) {
                        var result9 = parse_parameter();
                        if (result9 !== null) {
                            var result6 = [result8, result9];
                        } else {
                            var result6 = null;
                            pos = savedPos3;
                        }
                    } else {
                        var result6 = null;
                        pos = savedPos3;
                    }
                    var result7 = result6 !== null
                        ? (function (r) {
                        return r;
                    })(result6[1])
                        : null;
                    if (result7 !== null) {
                        var result5 = result7;
                    } else {
                        var result5 = null;
                        pos = savedPos2;
                    }
                    while (result5 !== null) {
                        result4.push(result5);
                        var savedPos2 = pos;
                        var savedPos3 = pos;
                        if (input.substr(pos, 1) === ",") {
                            var result8 = ",";
                            pos += 1;
                        } else {
                            var result8 = null;
                            if (reportMatchFailures) {
                                matchFailed("\",\"");
                            }
                        }
                        if (result8 !== null) {
                            var result9 = parse_parameter();
                            if (result9 !== null) {
                                var result6 = [result8, result9];
                            } else {
                                var result6 = null;
                                pos = savedPos3;
                            }
                        } else {
                            var result6 = null;
                            pos = savedPos3;
                        }
                        var result7 = result6 !== null
                            ? (function (r) {
                            return r;
                        })(result6[1])
                            : null;
                        if (result7 !== null) {
                            var result5 = result7;
                        } else {
                            var result5 = null;
                            pos = savedPos2;
                        }
                    }
                    if (result4 !== null) {
                        var result1 = [result3, result4];
                    } else {
                        var result1 = null;
                        pos = savedPos1;
                    }
                } else {
                    var result1 = null;
                    pos = savedPos1;
                }
                var result2 = result1 !== null
                    ? (function (s, rp) {
                    return s ? [s].concat(rp) : [];
                })(result1[0], result1[1])
                    : null;
                if (result2 !== null) {
                    var result0 = result2;
                } else {
                    var result0 = null;
                    pos = savedPos0;
                }


                cache[cacheKey] = {
                    nextPos:pos,
                    result:result0
                };
                return result0;
            }

            function parse_fnc() {
                var cacheKey = 'fnc@' + pos;
                var cachedResult = cache[cacheKey];
                if (cachedResult) {
                    pos = cachedResult.nextPos;
                    return cachedResult.result;
                }


                var savedPos0 = pos;
                var savedPos1 = pos;
                var result3 = parse_varName();
                if (result3 !== null) {
                    if (input.substr(pos, 1) === "(") {
                        var result4 = "(";
                        pos += 1;
                    } else {
                        var result4 = null;
                        if (reportMatchFailures) {
                            matchFailed("\"(\"");
                        }
                    }
                    if (result4 !== null) {
                        var result7 = parse_parameterArray();
                        var result5 = result7 !== null ? result7 : '';
                        if (result5 !== null) {
                            if (input.substr(pos, 1) === ")") {
                                var result6 = ")";
                                pos += 1;
                            } else {
                                var result6 = null;
                                if (reportMatchFailures) {
                                    matchFailed("\")\"");
                                }
                            }
                            if (result6 !== null) {
                                var result1 = [result3, result4, result5, result6];
                            } else {
                                var result1 = null;
                                pos = savedPos1;
                            }
                        } else {
                            var result1 = null;
                            pos = savedPos1;
                        }
                    } else {
                        var result1 = null;
                        pos = savedPos1;
                    }
                } else {
                    var result1 = null;
                    pos = savedPos1;
                }
                var result2 = result1 !== null
                    ? (function (n, pa) {
                    return {name:n, type:'fnc', parameter:pa };
                })(result1[0], result1[2])
                    : null;
                if (result2 !== null) {
                    var result0 = result2;
                } else {
                    var result0 = null;
                    pos = savedPos0;
                }


                cache[cacheKey] = {
                    nextPos:pos,
                    result:result0
                };
                return result0;
            }

            function parse_pathElement() {
                var cacheKey = 'pathElement@' + pos;
                var cachedResult = cache[cacheKey];
                if (cachedResult) {
                    pos = cachedResult.nextPos;
                    return cachedResult.result;
                }


                var result2 = parse_fnc();
                if (result2 !== null) {
                    var result0 = result2;
                } else {
                    var result1 = parse_var();
                    if (result1 !== null) {
                        var result0 = result1;
                    } else {
                        var result0 = null;
                        ;
                    }
                    ;
                }


                cache[cacheKey] = {
                    nextPos:pos,
                    result:result0
                };
                return result0;
            }

            function parse_path() {
                var cacheKey = 'path@' + pos;
                var cachedResult = cache[cacheKey];
                if (cachedResult) {
                    pos = cachedResult.nextPos;
                    return cachedResult.result;
                }


                var savedPos0 = pos;
                var savedPos1 = pos;
                var result3 = parse_pathElement();
                if (result3 !== null) {
                    var result4 = [];
                    var savedPos2 = pos;
                    var savedPos3 = pos;
                    if (input.substr(pos, 1) === ".") {
                        var result8 = ".";
                        pos += 1;
                    } else {
                        var result8 = null;
                        if (reportMatchFailures) {
                            matchFailed("\".\"");
                        }
                    }
                    if (result8 !== null) {
                        var result9 = parse_pathElement();
                        if (result9 !== null) {
                            var result6 = [result8, result9];
                        } else {
                            var result6 = null;
                            pos = savedPos3;
                        }
                    } else {
                        var result6 = null;
                        pos = savedPos3;
                    }
                    var result7 = result6 !== null
                        ? (function (r) {
                        return r;
                    })(result6[1])
                        : null;
                    if (result7 !== null) {
                        var result5 = result7;
                    } else {
                        var result5 = null;
                        pos = savedPos2;
                    }
                    while (result5 !== null) {
                        result4.push(result5);
                        var savedPos2 = pos;
                        var savedPos3 = pos;
                        if (input.substr(pos, 1) === ".") {
                            var result8 = ".";
                            pos += 1;
                        } else {
                            var result8 = null;
                            if (reportMatchFailures) {
                                matchFailed("\".\"");
                            }
                        }
                        if (result8 !== null) {
                            var result9 = parse_pathElement();
                            if (result9 !== null) {
                                var result6 = [result8, result9];
                            } else {
                                var result6 = null;
                                pos = savedPos3;
                            }
                        } else {
                            var result6 = null;
                            pos = savedPos3;
                        }
                        var result7 = result6 !== null
                            ? (function (r) {
                            return r;
                        })(result6[1])
                            : null;
                        if (result7 !== null) {
                            var result5 = result7;
                        } else {
                            var result5 = null;
                            pos = savedPos2;
                        }
                    }
                    if (result4 !== null) {
                        var result1 = [result3, result4];
                    } else {
                        var result1 = null;
                        pos = savedPos1;
                    }
                } else {
                    var result1 = null;
                    pos = savedPos1;
                }
                var result2 = result1 !== null
                    ? (function (s, rp) {
                    return [s].concat(rp);
                })(result1[0], result1[1])
                    : null;
                if (result2 !== null) {
                    var result0 = result2;
                } else {
                    var result0 = null;
                    pos = savedPos0;
                }


                cache[cacheKey] = {
                    nextPos:pos,
                    result:result0
                };
                return result0;
            }

            function parse_binding() {
                var cacheKey = 'binding@' + pos;
                var cachedResult = cache[cacheKey];
                if (cachedResult) {
                    pos = cachedResult.nextPos;
                    return cachedResult.result;
                }


                var savedPos0 = pos;
                var savedPos1 = pos;
                if (input.substr(pos, 1) === "{") {
                    var result3 = "{";
                    pos += 1;
                } else {
                    var result3 = null;
                    if (reportMatchFailures) {
                        matchFailed("\"{\"");
                    }
                }
                if (result3 !== null) {
                    var result4 = parse_path();
                    if (result4 !== null) {
                        if (input.substr(pos, 1) === "}") {
                            var result5 = "}";
                            pos += 1;
                        } else {
                            var result5 = null;
                            if (reportMatchFailures) {
                                matchFailed("\"}\"");
                            }
                        }
                        if (result5 !== null) {
                            var result1 = [result3, result4, result5];
                        } else {
                            var result1 = null;
                            pos = savedPos1;
                        }
                    } else {
                        var result1 = null;
                        pos = savedPos1;
                    }
                } else {
                    var result1 = null;
                    pos = savedPos1;
                }
                var result2 = result1 !== null
                    ? (function (path) {
                    return path ? {path:path, type:'normal'} : false;
                })(result1[1])
                    : null;
                if (result2 !== null) {
                    var result0 = result2;
                } else {
                    var result0 = null;
                    pos = savedPos0;
                }


                cache[cacheKey] = {
                    nextPos:pos,
                    result:result0
                };
                return result0;
            }

            function parse_twoWayBinding() {
                var cacheKey = 'twoWayBinding@' + pos;
                var cachedResult = cache[cacheKey];
                if (cachedResult) {
                    pos = cachedResult.nextPos;
                    return cachedResult.result;
                }


                var savedPos0 = pos;
                var savedPos1 = pos;
                if (input.substr(pos, 1) === "{") {
                    var result3 = "{";
                    pos += 1;
                } else {
                    var result3 = null;
                    if (reportMatchFailures) {
                        matchFailed("\"{\"");
                    }
                }
                if (result3 !== null) {
                    var result4 = parse_binding();
                    if (result4 !== null) {
                        if (input.substr(pos, 1) === "}") {
                            var result5 = "}";
                            pos += 1;
                        } else {
                            var result5 = null;
                            if (reportMatchFailures) {
                                matchFailed("\"}\"");
                            }
                        }
                        if (result5 !== null) {
                            var result1 = [result3, result4, result5];
                        } else {
                            var result1 = null;
                            pos = savedPos1;
                        }
                    } else {
                        var result1 = null;
                        pos = savedPos1;
                    }
                } else {
                    var result1 = null;
                    pos = savedPos1;
                }
                var result2 = result1 !== null
                    ? (function (b) {
                    b.type = 'twoWay';
                    return b;
                })(result1[1])
                    : null;
                if (result2 !== null) {
                    var result0 = result2;
                } else {
                    var result0 = null;
                    pos = savedPos0;
                }


                cache[cacheKey] = {
                    nextPos:pos,
                    result:result0
                };
                return result0;
            }

            function parse_staticBinding() {
                var cacheKey = 'staticBinding@' + pos;
                var cachedResult = cache[cacheKey];
                if (cachedResult) {
                    pos = cachedResult.nextPos;
                    return cachedResult.result;
                }


                var savedPos0 = pos;
                var savedPos1 = pos;
                if (input.substr(pos, 1) === "$") {
                    var result3 = "$";
                    pos += 1;
                } else {
                    var result3 = null;
                    if (reportMatchFailures) {
                        matchFailed("\"$\"");
                    }
                }
                if (result3 !== null) {
                    var result4 = parse_binding();
                    if (result4 !== null) {
                        var result1 = [result3, result4];
                    } else {
                        var result1 = null;
                        pos = savedPos1;
                    }
                } else {
                    var result1 = null;
                    pos = savedPos1;
                }
                var result2 = result1 !== null
                    ? (function (b) {
                    b.type = 'static';
                    return b;
                })(result1[1])
                    : null;
                if (result2 !== null) {
                    var result0 = result2;
                } else {
                    var result0 = null;
                    pos = savedPos0;
                }


                cache[cacheKey] = {
                    nextPos:pos,
                    result:result0
                };
                return result0;
            }

            function parse_text() {
                var cacheKey = 'text@' + pos;
                var cachedResult = cache[cacheKey];
                if (cachedResult) {
                    pos = cachedResult.nextPos;
                    return cachedResult.result;
                }


                var savedPos0 = pos;
                var result7 = parse_twoWayBinding();
                var result8 = result7 !== null
                    ? (function (t) {
                    return [t];
                })(result7)
                    : null;
                if (result8 !== null) {
                    var result6 = result8;
                } else {
                    var result6 = null;
                    pos = savedPos0;
                }
                if (result6 !== null) {
                    var result0 = result6;
                } else {
                    var result1 = [];
                    var result5 = parse_staticBinding();
                    if (result5 !== null) {
                        var result2 = result5;
                    } else {
                        var result4 = parse_binding();
                        if (result4 !== null) {
                            var result2 = result4;
                        } else {
                            if (input.length > pos) {
                                var result3 = input.charAt(pos);
                                pos++;
                            } else {
                                var result3 = null;
                                if (reportMatchFailures) {
                                    matchFailed('any character');
                                }
                            }
                            if (result3 !== null) {
                                var result2 = result3;
                            } else {
                                var result2 = null;
                                ;
                            }
                            ;
                        }
                        ;
                    }
                    while (result2 !== null) {
                        result1.push(result2);
                        var result5 = parse_staticBinding();
                        if (result5 !== null) {
                            var result2 = result5;
                        } else {
                            var result4 = parse_binding();
                            if (result4 !== null) {
                                var result2 = result4;
                            } else {
                                if (input.length > pos) {
                                    var result3 = input.charAt(pos);
                                    pos++;
                                } else {
                                    var result3 = null;
                                    if (reportMatchFailures) {
                                        matchFailed('any character');
                                    }
                                }
                                if (result3 !== null) {
                                    var result2 = result3;
                                } else {
                                    var result2 = null;
                                    ;
                                }
                                ;
                            }
                            ;
                        }
                    }
                    if (result1 !== null) {
                        var result0 = result1;
                    } else {
                        var result0 = null;
                        ;
                    }
                    ;
                }


                cache[cacheKey] = {
                    nextPos:pos,
                    result:result0
                };
                return result0;
            }

            function buildErrorMessage() {
                function buildExpected(failuresExpected) {
                    failuresExpected.sort();

                    var lastFailure = null;
                    var failuresExpectedUnique = [];
                    for (var i = 0; i < failuresExpected.length; i++) {
                        if (failuresExpected[i] !== lastFailure) {
                            failuresExpectedUnique.push(failuresExpected[i]);
                            lastFailure = failuresExpected[i];
                        }
                    }

                    switch (failuresExpectedUnique.length) {
                        case 0:
                            return 'end of input';
                        case 1:
                            return failuresExpectedUnique[0];
                        default:
                            return failuresExpectedUnique.slice(0, failuresExpectedUnique.length - 1).join(', ')
                                + ' or '
                                + failuresExpectedUnique[failuresExpectedUnique.length - 1];
                    }
                }

                var expected = buildExpected(rightmostMatchFailuresExpected);
                var actualPos = Math.max(pos, rightmostMatchFailuresPos);
                var actual = actualPos < input.length
                    ? quote(input.charAt(actualPos))
                    : 'end of input';

                return 'Expected ' + expected + ' but ' + actual + ' found.';
            }

            function computeErrorPosition() {
                /*
                 * The first idea was to use |String.split| to break the input up to the
                 * error position along newlines and derive the line and column from
                 * there. However IE's |split| implementation is so broken that it was
                 * enough to prevent it.
                 */

                var line = 1;
                var column = 1;
                var seenCR = false;

                for (var i = 0; i < rightmostMatchFailuresPos; i++) {
                    var ch = input.charAt(i);
                    if (ch === '\n') {
                        if (!seenCR) {
                            line++;
                        }
                        column = 1;
                        seenCR = false;
                    } else if (ch === '\r' | ch === '\u2028' || ch === '\u2029') {
                        line++;
                        column = 1;
                        seenCR = true;
                    } else {
                        column++;
                        seenCR = false;
                    }
                }

                return { line:line, column:column };
            }


            var result = parseFunctions[startRule]();

            /*
             * The parser is now in one of the following three states:
             *
             * 1. The parser successfully parsed the whole input.
             *
             *    - |result !== null|
             *    - |pos === input.length|
             *    - |rightmostMatchFailuresExpected| may or may not contain something
             *
             * 2. The parser successfully parsed only a part of the input.
             *
             *    - |result !== null|
             *    - |pos < input.length|
             *    - |rightmostMatchFailuresExpected| may or may not contain something
             *
             * 3. The parser did not successfully parse any part of the input.
             *
             *   - |result === null|
             *   - |pos === 0|
             *   - |rightmostMatchFailuresExpected| contains at least one failure
             *
             * All code following this comment (including called functions) must
             * handle these states.
             */
            if (result === null || pos !== input.length) {
                var errorPosition = computeErrorPosition();
                throw new this.SyntaxError(
                    buildErrorMessage(),
                    errorPosition.line,
                    errorPosition.column
                );
            }

            return result;
        },

        /* Returns the parser source code. */
        toSource:function () {
            return this._source;
        }
    };

    /* Thrown when a parser encounters a syntax error. */

    result.SyntaxError = function (message, line, column) {
        this.name = 'SyntaxError';
        this.message = message;
        this.line = line;
        this.column = column;
    };

    result.SyntaxError.prototype = Error.prototype;

    return result;
});