define(
//begin v1.x content
{
	"months-format-narrow": [
		"1월",
		"2월",
		"3월",
		"4월",
		"5월",
		"6월",
		"7월",
		"8월",
		"9월",
		"10월",
		"11월",
		"12월"
	],
	"field-weekday": "요일",
	"dateFormatItem-yQQQ": "y년 QQQ",
	"dateFormatItem-yMEd": "yyyy. M. d. EEE",
	"dateFormatItem-MMMEd": "MMM d일 (E)",
	"eraNarrow": [
		"기원전",
		"서기"
	],
	"dateFormat-long": "y년 M월 d일",
	"months-format-wide": [
		"1월",
		"2월",
		"3월",
		"4월",
		"5월",
		"6월",
		"7월",
		"8월",
		"9월",
		"10월",
		"11월",
		"12월"
	],
	"dateTimeFormat-medium": "{1} {0}",
	"dateFormatItem-EEEd": "d일 EEE",
	"dayPeriods-format-wide-pm": "오후",
	"dateFormat-full": "y년 M월 d일 EEEE",
	"dateFormatItem-Md": "M. d.",
	"field-era": "연호",
	"dateFormatItem-yM": "yyyy. M.",
	"months-standAlone-wide": [
		"1월",
		"2월",
		"3월",
		"4월",
		"5월",
		"6월",
		"7월",
		"8월",
		"9월",
		"10월",
		"11월",
		"12월"
	],
	"timeFormat-short": "a h:mm",
	"quarters-format-wide": [
		"제 1/4분기",
		"제 2/4분기",
		"제 3/4분기",
		"제 4/4분기"
	],
	"timeFormat-long": "a h시 m분 s초 z",
	"field-year": "년",
	"dateFormatItem-yMMM": "y년 MMM",
	"dateFormatItem-yQ": "y년 Q분기",
	"field-hour": "시",
	"dateFormatItem-MMdd": "MM. dd",
	"months-format-abbr": [
		"1월",
		"2월",
		"3월",
		"4월",
		"5월",
		"6월",
		"7월",
		"8월",
		"9월",
		"10월",
		"11월",
		"12월"
	],
	"dateFormatItem-yyQ": "yy년 Q분기",
	"timeFormat-full": "a h시 m분 s초 zzzz",
	"field-day-relative+0": "오늘",
	"field-day-relative+1": "내일",
	"field-day-relative+2": "모레",
	"dateFormatItem-H": "H시",
	"field-day-relative+3": "3일후",
	"months-standAlone-abbr": [
		"1월",
		"2월",
		"3월",
		"4월",
		"5월",
		"6월",
		"7월",
		"8월",
		"9월",
		"10월",
		"11월",
		"12월"
	],
	"quarters-format-abbr": [
		"1분기",
		"2분기",
		"3분기",
		"4분기"
	],
	"quarters-standAlone-wide": [
		"제 1/4분기",
		"제 2/4분기",
		"제 3/4분기",
		"제 4/4분기"
	],
	"dateFormatItem-HHmmss": "HH:mm:ss",
	"dateFormatItem-M": "M월",
	"days-standAlone-wide": [
		"일요일",
		"월요일",
		"화요일",
		"수요일",
		"목요일",
		"금요일",
		"토요일"
	],
	"dateFormatItem-yyMMM": "yy년 MMM",
	"timeFormat-medium": "a h:mm:ss",
	"dateFormatItem-Hm": "HH:mm",
	"quarters-standAlone-abbr": [
		"1분기",
		"2분기",
		"3분기",
		"4분기"
	],
	"eraAbbr": [
		"기원전",
		"서기"
	],
	"field-minute": "분",
	"field-dayperiod": "오전/오후",
	"days-standAlone-abbr": [
		"일",
		"월",
		"화",
		"수",
		"목",
		"금",
		"토"
	],
	"dateFormatItem-d": "d일",
	"dateFormatItem-ms": "mm:ss",
	"field-day-relative+-1": "어제",
	"dateFormatItem-h": "a h시",
	"dateTimeFormat-long": "{1} {0}",
	"field-day-relative+-2": "그저께",
	"field-day-relative+-3": "그끄제",
	"dateFormatItem-MMMd": "MMM d일",
	"dateFormatItem-MEd": "M. d. (E)",
	"dateTimeFormat-full": "{1} {0}",
	"field-day": "일",
	"days-format-wide": [
		"일요일",
		"월요일",
		"화요일",
		"수요일",
		"목요일",
		"금요일",
		"토요일"
	],
	"field-zone": "시간대",
	"dateFormatItem-yyyyMM": "yyyy. MM",
	"dateFormatItem-y": "y년",
	"months-standAlone-narrow": [
		"1월",
		"2월",
		"3월",
		"4월",
		"5월",
		"6월",
		"7월",
		"8월",
		"9월",
		"10월",
		"11월",
		"12월"
	],
	"dateFormatItem-yyMM": "YY. M.",
	"dateFormatItem-hm": "a h:mm",
	"days-format-abbr": [
		"일",
		"월",
		"화",
		"수",
		"목",
		"금",
		"토"
	],
	"dateFormatItem-yMMMd": "y년 MMM d일",
	"eraNames": [
		"서력기원전",
		"서력기원"
	],
	"days-format-narrow": [
		"일",
		"월",
		"화",
		"수",
		"목",
		"금",
		"토"
	],
	"field-month": "월",
	"days-standAlone-narrow": [
		"일",
		"월",
		"화",
		"수",
		"목",
		"금",
		"토"
	],
	"dateFormatItem-MMM": "LLL",
	"dayPeriods-format-wide-am": "오전",
	"dateFormat-short": "yy. M. d.",
	"field-second": "초",
	"dateFormatItem-yMMMEd": "y년 MMM d일 EEE",
	"dateFormatItem-Ed": "d일 (E)",
	"field-week": "주",
	"dateFormat-medium": "yyyy. M. d.",
	"dateFormatItem-mmss": "mm:ss",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-Hms": "H시 m분 s초",
	"dateFormatItem-hms": "a h:mm:ss"
}
//end v1.x content
);