var ___v1ew = [];  
   var previous = "", res, current, title;;
___v1ew.push("\n");
___v1ew.push("\n");
 if(selected && selected.length) { ;___v1ew.push("\n");
___v1ew.push("	<div id='selected'>\n");
___v1ew.push("		    "); for(var i =0; i < selected.length; i++){;___v1ew.push("\n");
___v1ew.push("				");  current = selected[i];
		 			title = (current.title ? current.title: current.name);
					res = calculateDisplay(previous, title);
					name = normalizeName(current.name) ;___v1ew.push("\n");
___v1ew.push("		<div class=\"topCorner\"><div>&nbsp;</div></div>\n");
___v1ew.push("		<div class=\"content\">\n");
___v1ew.push("			    <a href=\"#&who=");___v1ew.push((jQuery.View.EJS.text(name)));___v1ew.push("\" class='selected choice ");___v1ew.push((jQuery.View.EJS.text(current.type)));___v1ew.push("' style=\"padding-left: ");___v1ew.push((jQuery.View.EJS.text( res.length * 20)));___v1ew.push("px\">\n");
___v1ew.push("			    	<span class='remove' title=\"close\"></span>\n");
___v1ew.push("					");___v1ew.push((jQuery.View.EJS.text(res.name.replace("jQuery","$"))));___v1ew.push("\n");
___v1ew.push("					\n");
___v1ew.push("				</a>\n");
___v1ew.push("				"); previous = title;___v1ew.push("\n");
___v1ew.push("		</div>\n");
___v1ew.push("		<div class=\"bottomCorner\"><div>&nbsp;</div></div>\n");
___v1ew.push("			"); if(i<(selected.length-1)){ ;___v1ew.push("\n");
___v1ew.push("		<div class=\"spacer\"><div>&nbsp;</div></div>\n");
___v1ew.push("			");};___v1ew.push("\n");
___v1ew.push("			");};___v1ew.push("\n");
___v1ew.push("	</div>\n");
};___v1ew.push("\n");
___v1ew.push("<div id='results' style=\"display: ");___v1ew.push((jQuery.View.EJS.text( hide? 'none' : 'block')));___v1ew.push("\">\n");
___v1ew.push("	<div class=\"topCorner\"><div>&nbsp;</div></div>\n");
___v1ew.push("	<div class=\"content\">\n");
___v1ew.push("	    "); for(var i =0; i < list.length; i++){;___v1ew.push("\n");
___v1ew.push("			"); current = list[i];
			   if(current.hide){ continue; }
			   title = (current.title ? current.title: current.name);
	           res = calculateDisplay(previous, title);
			   name = normalizeName(current.name) ;___v1ew.push("\n");
___v1ew.push("		    <a href=\"");___v1ew.push((jQuery.View.EJS.text(current.type == 'prototype' || current.type == 'static' ? 'javascript://': '#&who='+name)));___v1ew.push("\" class='result choice ");___v1ew.push((jQuery.View.EJS.text(current.type)));___v1ew.push("' style=\"padding-left: ");___v1ew.push((jQuery.View.EJS.text( res.length * 20)));___v1ew.push("px\">\n");
___v1ew.push("		    	");___v1ew.push((jQuery.View.EJS.text(res.name.replace("jQuery","$"))));___v1ew.push("\n");
___v1ew.push("			</a>\n");
___v1ew.push("			"); previous = title;___v1ew.push("\n");
___v1ew.push("		");};___v1ew.push("\n");
___v1ew.push("	</div>\n");
___v1ew.push("	<div class=\"bottomCorner\"><div>&nbsp;</div></div>\n");
___v1ew.push("</div>\n");
___v1ew.push("\n");
___v1ew.push("\n");
;