// Generated by CoffeeScript 1.3.3
(function() {
  "use strict";

  /*
  Directive that places focus on the element it is applied to when the expression it binds to evaluates to true.
  */

  window.todomvc.directive("todoFocus", function($timeout) {
    return function(scope, elem, attrs) {
      return scope.$watch(attrs.todoFocus, function(newval) {
        if (newval) {
          return $timeout((function() {
            return elem[0].focus();
          }), 0, false);
        }
      });
    };
  });

}).call(this);
