// Generated by CoffeeScript 1.3.3
(function() {
  "use strict";

  /*
  Directive that executes an expression when the element it is applied to loses focus.
  */

  window.todomvc.directive("todoBlur", function() {
    return function(scope, elem, attrs) {
      return elem.bind("blur", function() {
        return scope.$apply(attrs.todoBlur);
      });
    };
  });

}).call(this);
