define(
//begin v1.x content
{
	"field-weekday": "曜日",
	"dateFormatItem-yQQQ": "yQQQ",
	"dateFormatItem-yMEd": "y/M/d(EEE)",
	"dateFormatItem-MMMEd": "M月d日(E)",
	"eraNarrow": [
		"BC",
		"AD"
	],
	"dateFormat-long": "y年M月d日",
	"months-format-wide": [
		"1月",
		"2月",
		"3月",
		"4月",
		"5月",
		"6月",
		"7月",
		"8月",
		"9月",
		"10月",
		"11月",
		"12月"
	],
	"dateTimeFormat-medium": "{1} {0}",
	"dayPeriods-format-wide-pm": "午後",
	"dateFormat-full": "y年M月d日EEEE",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-yMd": "y/M/d",
	"field-era": "時代",
	"dateFormatItem-yM": "y/M",
	"months-standAlone-wide": [
		"1月",
		"2月",
		"3月",
		"4月",
		"5月",
		"6月",
		"7月",
		"8月",
		"9月",
		"10月",
		"11月",
		"12月"
	],
	"timeFormat-short": "H:mm",
	"quarters-format-wide": [
		"第1四半期",
		"第2四半期",
		"第3四半期",
		"第4四半期"
	],
	"timeFormat-long": "H:mm:ss z",
	"field-year": "年",
	"dateFormatItem-yMMM": "y年M月",
	"dateFormatItem-yQ": "y/Q",
	"field-hour": "時",
	"dateFormatItem-MMdd": "MM/dd",
	"months-format-abbr": [
		"1月",
		"2月",
		"3月",
		"4月",
		"5月",
		"6月",
		"7月",
		"8月",
		"9月",
		"10月",
		"11月",
		"12月"
	],
	"dateFormatItem-yyQ": "yy/Q",
	"timeFormat-full": "H時mm分ss秒 zzzz",
	"field-day-relative+0": "今日",
	"field-day-relative+1": "明日",
	"field-day-relative+2": "明後日",
	"dateFormatItem-H": "H時",
	"field-day-relative+3": "3日後",
	"months-standAlone-abbr": [
		"1月",
		"2月",
		"3月",
		"4月",
		"5月",
		"6月",
		"7月",
		"8月",
		"9月",
		"10月",
		"11月",
		"12月"
	],
	"quarters-format-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"quarters-standAlone-wide": [
		"第1四半期",
		"第2四半期",
		"第3四半期",
		"第4四半期"
	],
	"dateFormatItem-M": "M月",
	"days-standAlone-wide": [
		"日曜日",
		"月曜日",
		"火曜日",
		"水曜日",
		"木曜日",
		"金曜日",
		"土曜日"
	],
	"dateFormatItem-yyMMM": "y年M月",
	"timeFormat-medium": "H:mm:ss",
	"dateFormatItem-Hm": "H:mm",
	"eraAbbr": [
		"BC",
		"AD"
	],
	"field-minute": "分",
	"field-dayperiod": "午前/午後",
	"days-standAlone-abbr": [
		"日",
		"月",
		"火",
		"水",
		"木",
		"金",
		"土"
	],
	"dateFormatItem-d": "d日",
	"dateFormatItem-ms": "mm:ss",
	"field-day-relative+-1": "昨日",
	"dateFormatItem-h": "ah時",
	"dateTimeFormat-long": "{1}{0}",
	"field-day-relative+-2": "一昨日",
	"field-day-relative+-3": "3日前",
	"dateFormatItem-MMMd": "M月d日",
	"dateFormatItem-MEd": "M/d(E)",
	"dateTimeFormat-full": "{1}{0}",
	"field-day": "日",
	"days-format-wide": [
		"日曜日",
		"月曜日",
		"火曜日",
		"水曜日",
		"木曜日",
		"金曜日",
		"土曜日"
	],
	"field-zone": "タイムゾーン",
	"dateFormatItem-yyyyMM": "yyyy/MM",
	"dateFormatItem-y": "y年",
	"months-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"dateFormatItem-hm": "ah:mm",
	"dateFormatItem-GGGGyMd": "GGGGy年M月d日",
	"days-format-abbr": [
		"日",
		"月",
		"火",
		"水",
		"木",
		"金",
		"土"
	],
	"dateFormatItem-yMMMd": "y年M月d日",
	"eraNames": [
		"紀元前",
		"西暦"
	],
	"days-format-narrow": [
		"日",
		"月",
		"火",
		"水",
		"木",
		"金",
		"土"
	],
	"field-month": "月",
	"days-standAlone-narrow": [
		"日",
		"月",
		"火",
		"水",
		"木",
		"金",
		"土"
	],
	"dateFormatItem-MMM": "LLL",
	"dayPeriods-format-wide-am": "午前",
	"dateFormat-short": "yy/MM/dd",
	"field-second": "秒",
	"dateFormatItem-yMMMEd": "y年M月d日(EEE)",
	"dateFormatItem-Ed": "d日(EEE)",
	"field-week": "週",
	"dateFormat-medium": "yyyy/MM/dd",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-hms": "ah:mm:ss",
	"dateFormatItem-yyyy": "y年"
}
//end v1.x content
);