// Generated by CoffeeScript 1.3.3
(function() {
  "use strict";

  /*
  The main TodoMVC app module.
  
  @type {angular.Module}
  */

  window.todomvc = angular.module("window.todomvc", ['']);

}).call(this);
