// This file was autogenerated by /Users/thanpolas/Projects/todoAppMantri/node_modules/mantri/lib/../node_modules/closure-tools/closure-bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('js/app.js', ['Todos.app'], ['Todos.Router', 'Todos.ctrls.Entries', 'Todos.models.Store', 'Todos.views.Application']);
goog.addDependency('js/app/controllers/entries.js', ['Todos.ctrls.Entries'], []);
goog.addDependency('js/app/controllers/todos.js', ['Todos.ctrls.Todos'], []);
goog.addDependency('js/app/models/store.js', ['Todos.models.Store'], ['Todos.models.Todo']);
goog.addDependency('js/app/models/todo.js', ['Todos.models.Todo'], []);
goog.addDependency('js/app/router.js', ['Todos.Router'], ['Todos.ctrls.Todos', 'Todos.helper', 'Todos.views.Items']);
goog.addDependency('js/app/specs/helper.js', ['Todos.helper'], ['Todos.todoMVCspec']);
goog.addDependency('js/app/specs/todoMVC.js', ['Todos.todoMVCspec'], []);
goog.addDependency('js/app/views/application.js', ['Todos.views.Application'], ['Todos.views.ClearButton', 'Todos.views.Filters', 'Todos.views.Stats']);
goog.addDependency('js/app/views/clear_button.js', ['Todos.views.ClearButton'], []);
goog.addDependency('js/app/views/filters.js', ['Todos.views.Filters'], []);
goog.addDependency('js/app/views/items.js', ['Todos.views.Items'], []);
goog.addDependency('js/app/views/stats.js', ['Todos.views.Stats'], []);
