/*
 Olives

 The MIT License (MIT)

 Copyright(c) 2012 Olivier Scherrer <pode.fr@gmail.com> - Olivier Wietrich <olivier.wietrich@gmail.com>
*/
define("Olives/DomUtils",["Tools"],function(){return{getNodes:function(e,g){return e instanceof HTMLElement?(e.parentNode||document.createDocumentFragment().appendChild(e),e.parentNode.querySelectorAll(g||"*")):false},getDataset:function(e){var g=0,f,k={},b,a;if(e instanceof HTMLElement){for(f=e.attributes.length;g<f;g++)b=e.attributes[g].name.split("-"),b.shift()=="data"&&(k[a=b.join("-")]=e.getAttribute("data-"+a));return k}else return false}}});
define("Olives/Event-plugin",function(){return function(e){this.listen=function(g,f,k,b){g.addEventListener(f,function(a){e[k].call(e,a,g)},b=="true")}}});
define("Olives/LocalStore",["Store","Tools"],function(e,g){function f(){var f=null,b=function(){localStorage.setItem(f,this.toJSON())};this.sync=function(a){return typeof a=="string"?(f=a,a=JSON.parse(localStorage.getItem(a)),g.loop(a,function(a,h){this.has(h)||this.set(h,a)},this),b.call(this),true):false};this.watch("added",b,this);this.watch("updated",b,this);this.watch("deleted",b,this)}return function(g){f.prototype=new e(g);return new f}});
define("Olives/Model-plugin",["Store","Observable","Tools","Olives/DomUtils"],function(e,g,f,k){return function(b,a){var d=null,h={},i={};this.observers={};this.setModel=function(l){return l instanceof e?(d=l,true):false};this.getModel=function(){return d};this.ItemRenderer=function(l,a){var c=null,h=null,b=null,i=null,g=null;this.setRenderer=function(a){c=a;return true};this.getRenderer=function(){return c};this.setRootNode=function(c){return c instanceof HTMLElement?(b=c,c=b.querySelector("*"),
this.setRenderer(c),c&&b.removeChild(c),true):false};this.getRootNode=function(){return b};this.setPlugins=function(c){h=c;return true};this.getPlugins=function(){return h};this.items=new e([]);this.setStart=function(c){return i=parseInt(c,10)};this.getStart=function(){return i};this.setNb=function(c){return g=c=="*"?c:parseInt(c,10)};this.getNb=function(){return g};this.addItem=function(c){var a;return typeof c=="number"&&!this.items.get(c)?(a=this.create(c))?((c=this.getNextItem(c))?b.insertBefore(a,
c):b.appendChild(a),true):false:false};this.getNextItem=function(c){return this.items.alter("slice",c+1).filter(function(c){if(c instanceof HTMLElement)return true})[0]};this.removeItem=function(c){var a=this.items.get(c);return a?(b.removeChild(a),this.items.set(c),true):false};this.create=function(a){if(d.has(a)){var l=c.cloneNode(true),j=k.getNodes(l);f.toArray(j).forEach(function(c){c.setAttribute("data-"+h.name+"_id",a)});this.items.set(a,l);h.apply(l);return l}};this.render=function(){var c=
g=="*"?d.getNbItems():g,a=[];if(g!==null&&i!==null){this.items.loop(function(l,j){(j<i||j>=i+c||!d.has(j))&&a.push(j)},this);a.sort(f.compareNumbers).reverse().forEach(this.removeItem,this);for(var l=i,j=c+i;l<j;l++)this.addItem(l);return true}else return false};this.setPlugins(l);this.setRootNode(a)};this.setItemRenderer=function(a,j){i[a||"default"]=j};this.getItemRenderer=function(a){return i[a]};this.foreach=function(a,j,c,h){var b=new this.ItemRenderer(this.plugins,a);b.setStart(c||0);b.setNb(h||
"*");b.render();d.watch("added",b.render,b);d.watch("deleted",function(c){b.render();this.observers[c]&&this.observers[c].forEach(function(c){d.unwatchValue(c)},this);delete this.observers[c]},this);this.setItemRenderer(j,b)};this.updateStart=function(a,j){var c=this.getItemRenderer(a);return c?(c.setStart(j),true):false};this.updateNb=function(a,j){var c=this.getItemRenderer(a);return c?(c.setNb(j),true):false};this.refresh=function(a){return(a=this.getItemRenderer(a))?(a.render(),true):false};this.bind=
function(a,j,c){var c=c||"",b=a.getAttribute("data-"+this.plugins.name+"_id"),h=c.split("."),i=b||h.shift(),e=b?c:h.join("."),b=f.getNestedProperty(d.get(i),e),g=f.toArray(arguments).slice(3);if(b||b===0||b===false)this.execBinding.apply(this,[a,j,b].concat(g))||(a[j]=b);this.hasBinding(j)||a.addEventListener("change",function(){if(e){var b=d.get(i);f.setNestedProperty(b,c,a[j]);d.set(i,b)}else d.set(i,a[j])},true);this.observers[i]=this.observers[i]||[];this.observers[i].push(d.watchValue(i,function(c){this.execBinding.apply(this,
[a,j,f.getNestedProperty(c,e)].concat(g))||(a[j]=f.getNestedProperty(c,e))},this))};this.set=function(a){return a instanceof HTMLElement&&a.name?(d.set(a.name,a.value),true):false};this.form=function j(j){if(j&&j.nodeName=="FORM"){var c=this;j.addEventListener("submit",function(a){f.toArray(j.querySelectorAll("[name]")).forEach(c.set,c);a.preventDefault()},true);return true}else return false};this.addBinding=function(a,c){return a&&typeof a=="string"&&typeof c=="function"?(h[a]=c,true):false};this.execBinding=
function(a,c){return this.hasBinding(c)?(h[c].apply(a,Array.prototype.slice.call(arguments,2)),true):false};this.hasBinding=function(a){return h.hasOwnProperty(a)};this.getBinding=function(a){return h[a]};this.addBindings=function(a){return f.loop(a,function(a,b){this.addBinding(b,a)},this)};this.setModel(b);this.addBindings(a)}});
define("Olives/OObject",["StateMachine","Store","Olives/Plugins","Olives/DomUtils","Tools"],function(e,g,f,k,b){return function(a){var d=function(a){var c=i||document.createElement("div");if(a.template){typeof a.template=="string"?c.innerHTML=a.template.trim():a.template instanceof HTMLElement&&c.appendChild(a.template);if(c.childNodes.length>1)throw Error("UI.template should have only one parent node");else a.dom=c.childNodes[0];a.plugins.apply(a.dom)}else throw Error("UI.template must be set prior to render");
},h=function c(a,c,b){c&&(b?c.insertBefore(a.dom,b):c.appendChild(a.dom),i=c)},i=null,l=new e("Init",{Init:[["render",d,this,"Rendered"],["place",function(a,i){d(a);h.apply(null,b.toArray(arguments))},this,"Rendered"]],Rendered:[["place",h,this],["render",d,this]]});this.model=a instanceof g?a:new g;this.plugins=new f;this.dom=this.template=null;this.place=function(a,b){l.event("place",this,a,b)};this.render=function(){l.event("render",this)};this.setTemplateFromDom=function(a){return a instanceof
HTMLElement?(this.template=a,true):false};this.alive=function(a){return a instanceof HTMLElement?(this.setTemplateFromDom(a),this.place(a.parentNode,a.nextElementSibling),true):false}}});
define("Olives/Plugins",["Tools","Olives/DomUtils"],function(e,g){return function(){var f={},k=function(a){return a.trim()},b=function(a,b,h){b.split(";").forEach(function(b){var d=b.split(":"),b=d[0].trim(),d=d[1]?d[1].split(",").map(k):[];d.unshift(a);f[h]&&f[h][b]&&f[h][b].apply(f[h],d)})};this.add=function(a,b){var h=this;return typeof a=="string"&&typeof b=="object"&&b?(f[a]=b,b.plugins={name:a,apply:function(){return h.apply.apply(h,arguments)}},true):false};this.addAll=function(a){return e.loop(a,
function(a,b){this.add(b,a)},this)};this.get=function(a){return f[a]};this.del=function(a){return delete f[a]};this.apply=function(a){var d;return a instanceof HTMLElement?(d=g.getNodes(a),e.loop(e.toArray(d),function(a){e.loop(g.getDataset(a),function(i,d){b(a,i,d)})}),a):false}}});
define("Olives/Transport",["Observable","Tools"],function(e,g){return function(f,k){var b=null,a=null,d=new e;this.setIO=function(b){return b&&typeof b.connect=="function"?(a=b,true):false};this.getIO=function(){return a};this.connect=function(h){return typeof h=="string"?(b=a.connect(h),true):false};this.getSocket=function(){return b};this.on=function(a,i){b.on(a,i)};this.once=function(a,i){b.once(a,i)};this.emit=function(a,i,d){b.emit(a,i,d)};this.request=function(a,d,e,f){var c=Date.now()+Math.floor(Math.random()*
1E6),g=function(){e&&e.apply(f||null,arguments)};b[d.keptAlive?"on":"once"](c,g);d.__eventId__=c;b.emit(a,d);if(d.keptAlive)return function(){b.emit("disconnect-"+c);b.removeListener(c,g)}};this.listen=function(a,b,e,f){var c=a+"/"+b.path,k,m;d.hasTopic(c)||(g.mixin({method:"GET",keptAlive:true},b),m=this.request(a,b,function(a){d.notify(c,a)},this));k=d.watch(c,e,f);return function(){d.unwatch(k);d.hasTopic(c)||m()}};this.getListenObservable=function(){return d};this.setIO(f);this.connect(k)}});
define("Olives/UI-plugin",["Olives/OObject","Tools"],function(e,g){return function(f){var k={};this.place=function(b,a){if(k[a]instanceof e)k[a].place(b);else throw Error(a+" is not an OObject UI in place:"+a);};this.set=function(b,a){return typeof b=="string"&&a instanceof e?(k[b]=a,true):false};this.setAll=function(b){g.loop(b,function(a,b){this.set(b,a)},this)};this.get=function(b){return k[b]};this.setAll(f)}});
